### ISSUE TITLE
samplerate

### ISSUE THREAD

**Issue by Arcanum7** [mfg92/hantek1008py#2]
how to change rate from 440Hz to another frequency?
my case:
start device and write current (by bypass resistor) for >=24h to *.csv file
i think it will be enough if i get measurements 3 times at sec
what i have to edit and where?

**Comment by mfg92** [comment]
Yyou can use the --samplingrate parameter:

`csvexport.py --samplingrate 5`

You can use the --help flag to see all existing parameters:

`csvexport.py --help `

**Comment by achukhrov-ffr-team** [comment]
Good evening! Due to the characteristics of the Oscilloscope, its sampling rate is 2.4MHz, how can I do an experiment with such sampling rate using your code?
https://www.amazon.com/Automotive-Diagnostic-Oscilloscope-Programmable-Generator/dp/B01EZX2NXO

**Comment by mfg92** [comment]
First you must know that the device has to sampling modes, I call them 'rolling' and 'burst'.

- In 'rolling' mode the device can continuesly sample data for an unlimited amount of time. In this mode the max sample frequency is 440Hz. Have a look at the [help message](https://github.com/mfg92/hantek1008py/blob/master/csvexport.py#L511) of the corresponding cmd parameter.
- In 'burst' mode the device collects data only for a short period of time, in this mode much higher sampling rates are possible. Have look [here](https://github.com/mfg92/hantek1008py/blob/master/csvexport.py#L519).

You can change the [sampling mode](https://github.com/mfg92/hantek1008py/blob/master/csvexport.py#L508) using `--sampling mode`. 

So i guess the right call for you will be:
`csvexport.py  --samplingmode burst --nsperdiv 10`
This should sample around 25 value per channel every 10ns.

Notes:

- When less channels are used the sampling rate goes up.
- I would recommend you to call `csvexport.py --help` to see an explanation of all parameters and flags of csvexport.py.
- 2.4Mhz != 2,4 MSa/s

**Comment by achukhrov-ffr-team** [comment]
@mfg92 Thank you for your answer!
I tried to read sinusoidal signal with freq=200Hz and longitute = 1 sec
csvexport.py —samplingmode burst —nsperdiv 10
the answer was next
![image](https://user-images.githubusercontent.com/78736624/120990936-cc7b1f00-c789-11eb-8a3e-46dd89846787.png)
Could you tell me, please, what am I doing wrong?

**Comment by mfg92** [comment]
What you see is acutally expected. A single burst collects arround 500 datapoints. In your picture we can see the data of three burst. Between the bursts no data is collected, this is a limitation of the device.

If you want to see a longer part of the sine wave you have to use a higher value for `--nsperdiv ` like 50 or 100 (this will of course reduce the time resolution).

Another option you can try is to use the rolle mode but only read out one single channel:
`csvexport.py mydata.csv -s 1 --samplingrate 440`
This will only capture the data from channel 1. The actual samlpingrate is higher when less channels are read out. So instead of the given 440 Hz the actual sampling rate will be arround `4.56*440Hz`. Perhaps this is enought for your needs. You can use `measuresamplingrate` to measure the actual sampling rate.
